version: "3.5"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_UMAMI_URL=${NEXT_PUBLIC_UMAMI_URL}
      - NEXT_PUBLIC_UMAMI_WEBSITE_ID=${NEXT_PUBLIC_UMAMI_WEBSITE_ID}
    ports:
      - 3000:3000
    depends_on:
      - database
    restart: on-failure

  umami:
    image: ghcr.io/umami-software/umami:postgresql-v2.7.0
    environment:
      - DATABASE_URL=${UMAMI_DATABASE_URL}
    ports:
      - 3001:3000
    depends_on:
      - database
    restart: on-failure

  database:
    image: postgres:13
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=innohub,umami
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    restart: on-failure
