services:
  database:
    container_name: innoverse-database
    build:
      context: ../postgres
    volumes:
      - ../postgres/pg-init-scripts:/docker-entrypoint-initdb.d
    env_file: ./../postgres/.env
    restart: on-failure
    networks:
      - backend

  strapi:
    container_name: innoverse-strapi
    build:
      context: ../strapi
    restart: unless-stopped
    env_file: ./../strapi/.env.production
    volumes:
      - ../strapi/config:/opt/app/config
      - ../strapi/src:/opt/app/src
      - ../strapi/package.json:/opt/package.json
      - ../strapi/yarn.lock:/opt/yarn.lock
      - ../strapi/.env:/opt/app/.env
      - ../strapi/public/uploads:/opt/app/public/uploads
      - ../strapi/types:/opt/app/types
    ports:
      - "1337:1337"
    depends_on:
      - database
      - cache
    networks:
      - backend

  cache:
    container_name: innoverse-cache
    build:
      context: ../redis
    environment:
      - REDIS_ARGS=--appendonly yes --appendfsync everysec
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ../cache:/data
    networks:
      - backend

  innoverse:
    container_name: innoverse
    build:
      context: ../app
      dockerfile: ../app/Dockerfile
    env_file:
      - ../app/.env.production
    ports:
      - 3000:3000
    depends_on:
      - strapi
      - database
      - cache
    restart: on-failure
    networks:
      - backend

networks:
  backend:
